blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name='about-page'),
    path('archive/', views.archive, name='archive-page'),
    path('contact/', views.contact, name='contact-page'),
    path('privacy/', views.privacy, name='privacy-page'),
    path('', views.PostList.as_view(), name='home'),
    path("<slug:slug>/", views.post_detail, name="post-page"),
]

nixverse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'body': forms.Textarea(attrs={'placeholder': 'Message'}),
        }

blog/views.py
from django.views import generic
from .models import Post
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'

def post_detail(request, slug):
    template_name = 'post.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()


    else:
        comment_form = CommentForm()



    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

def about(request):
    return render(request, 'about.html')

def archive(request):
    return render(request, 'archive.html')

def contact(request):
    return render(request, 'contact.html')

def privacy(request):
    return render(request, 'privacy.html')

templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>ABOUT</h1>
{% endblock content %}

templates/archive.html
{% extends 'base.html' %}
{% block content %}
<h1>ARCHIVE</h1>
{% endblock content %}

templates/base.html
{% load static %}
{% static "css/styles.css" as css %}
{% static "media/icon.png" as logo %}
<!DOCTYPE html>
<html lang="en">
<head>
	  {% if post.title %}
        <title>{{ post.title }} - Nixverse - Unix/Linux Tutorials</title>
    {% else %}
        <title>Nixverse - Unix/Linux Tutorials</title>
    {% endif %}
	<link rel="stylesheet" href="{{ css }}" title="external style sheet">
	<link rel="icon" href="{{ logo }}">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta charset="utf-8"/>
</head>
<body>
{% include 'menu.html' %}
<main>
{% block content %}{% endblock content %}
</main>
</body>
</html>

templates/comment.html
<br>
{# Showing comments. #}
{% for comment in comments %}
<div class="comment-box">
    <name>{{ comment.name }}</name>
    <comment-date> said on {{ comment.created_on | date:"F d, Y" }} </comment-date>
    <br>
    <pre class="body">{{ comment.body }}</pre>
</div>
{% endfor %}

<br>

{# Add new comment. #}
{% if new_comment %}
    <div class="comment-box" style="text-align:center">
    Your comment is awaiting moderation.
    </div>
{% else %}
    <div class="reply">
        <form action="" method="post"">
            {% csrf_token %}
            {{ comment_form.name }}
            {{ comment_form.email }}
            {{ comment_form.body }}
            <button type="submit" class="btn">Reply</button>
        </form>
    </div>
{% endif %}

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<h1>CONTACT</h1>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% for post in post_list %}
<a href="{% url 'post-page' post.slug  %}">
<div class="index">
    <h1>{{ post.title }}</h1>
    <date>{{ post.created_on | date:"F d, Y" }}</date>
</div>
</a>
<br>
{% endfor %}
{% endblock content %}

templates/menu.html
<div class="header"><a href="{% url 'home' %}">NIXVERSE</a></div>

<input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
<label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
</label>
<div id="sidebarMenu">
    <ul class="sidebarMenuInner">
        <li><a href="{% url 'home' %}" >Home</a></li>
        <li><a href="{% url 'about-page' %}" >About</a></li>
        <li><a href="{% url 'archive-page' %}" >Archive</a></li>
        <li><a href="{% url 'contact-page' %}" >Contact</a></li>
        <li><a href="{% url 'privacy-page' %}" >Privacy</a></li>
    </ul>
</div>

templates/post.html
{% extends 'base.html' %} {% block content %}
<a href="{% url 'post-page' post.slug %}">
<h1 class="post_title">{{ post.title }}</h1></a>
<date>{{ post.created_on | date:"F d, Y" }}</date>
<p>{{ post.content | safe }}</p>
{% endblock content %}

templates/privacy.html
{% extends 'base.html' %}
{% block content %}
<h1>PRIVACY</h1>
{% endblock content %}